makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme
include:
  - assets
  - README.md
baseurl: /pxt-snore/
show_downloads: true
